### ISSUE TITLE
analyze() and other functions not included in psycho 0.5.0

### ISSUE THREAD

**Issue by tianfeiwei** [neuropsychology/psycho.R#115]
I was trying to use the analyze function in psycho but r can't find the function.

```r
library(psycho)
results <- analyze(fit)
print(results)
```
"Error in analyze(fit) : could not find function "analyze""

**Comment by DominiqueMakowski** [comment]
@tianfeiwei This is indeed expected, as the goal is to re-implement analyze (named `report()`) in the [report](https://github.com/easystats/report) package, so that `psycho`'s scope can be recentred around psychology-related functionalities.

One caveat is that for the next few days, the report package is actually broken (see https://github.com/easystats/report/issues/56). Although it should be fixed soon, here are some workarounds:

- If you don't need the textual output but just the values, you can use the two functions: `parameters::model_parameters()` and `performance::model_performance()` (from the [parameters](https://github.com/easystats/parameters) and [performance](https://github.com/easystats/performance) packages, respectively). This will give you all the required values (basically, `analyze()` just used to add the text around these values).

- If you really need `analyze()`, one way is to downgrade psycho, before 0.5. You can 1) remove your current installation of psycho (`remove.packages("psycho)"`). Then, you can install the previous release via `devtools::install_github("neuropsychology/psycho.R@0.4.0")`

Apologies for the inconvenience, and let me know if that helps!
